schema_version: 1

context:
  name: escape_utils
  version: 1.3.0

package:
  name: rb-${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://rubygems.org/downloads/${{ name }}-${{ version }}.gem
    sha256: dffb7010922880ace6ceed642156c64e2a64620f27e0849f43bc4f68fd3c2c09

build:
  number: 2
  skip: win
  script:
    - gem install -N -l -V --norc --ignore-dependencies ${{ name }}-${{ version }}.gem
    - gem unpack ${{ name }}-${{ version }}.gem
    - cp ${{ name }}-*/LICENSE .

requirements:
  build:
    - ${{ compiler('c') }}
    - make
  host:
    - ruby >=2.7,<3
  run:
    - ruby >=2.7,<3

tests:
  - script:
      - ruby -r ${{ name }} -e 'exit 0'

about:
  license: MIT
  license_file: LICENSE
  summary: Faster string escaping routines for your ruby apps
  homepage: https://rubygems.org/gems/${{ name }}
  repository: https://github.com/brianmario/escape_utils
  documentation: https://www.rubydoc.info/gems/${{ name }}

extra:
  recipe-maintainers:
    - svengiegerich
    - janjagusch
